#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/RotateImage/PackagingFolder
addattr GraphicsWorkflow:Info "A small applet to rotate an image and save the resulting image, using ImageMagick. Transparency is attempted, but will depend on the input file type. Interactive." ./apps/GraphicsWorkflow/RotateImage
addattr GraphicsWorkflow:Info "A script to rotate an image and save the resulting image, using ImageMagick. Transparency is attempted, but will depend on the input file type. Non-Interactive." ./apps/GraphicsWorkflow/RotateImage-Noninteractive
package create -b rotateimage_0.1-3_gcc2.hpkg
sleep 0.5
package add rotateimage_0.1-3_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Rotate images" rotateimage_0.1-3_gcc2.hpkg
becopy rotateimage_0.1-3_gcc2.hpkg "/Storage/Haiku/My ports"
mv rotateimage_0.1-3_gcc2.hpkg /boot/home/projects/repo2
sync
