#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/RotateImage/PackagingFolder
package create -b rotateimage_0.1-2_gcc2.hpkg
sleep 0.5
package add rotateimage_0.1-2_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Rotate images" rotateimage_0.1-2_gcc2.hpkg
becopy rotateimage_0.1-2_gcc2.hpkg "/Storage/Haiku/My ports"
mv rotateimage_0.1-2_gcc2.hpkg /boot/home/projects/repo2
sync
