#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/CharcoalSketchImage/PackagingFolder
addattr GraphicsWorkshop:Info "A small applet to make a charcoalsketch of an image and save the resulting image, using ImageMagick. Transparency is attempted, but will depend on the input file type. Interactive." ./apps/GraphicsWorkflow/CharcoalSketchImage
addattr GraphicsWorkshop:Info "A script to make a charcoalsketch of  an image and save the resulting image, using ImageMagick. Transparency is attempted, but will depend on the input file type. Non-Interactive." ./apps/GraphicsWorkflow/CharcoalSketchImage-Noninteractive
package create -b charcoalsketchimage_0.1-2_gcc2.hpkg
sleep 0.5
package add charcoalsketchimage_0.1-2_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Make charcoal sketch of image" charcoalsketchimage_0.1-2_gcc2.hpkg
becopy charcoalsketchimage_0.1-2_gcc2.hpkg "/Storage/Haiku/My ports"
mv charcoalsketchimage_0.1-2_gcc2.hpkg /boot/home/projects/repo2
sync
