#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/CharcoalSketchImage/
mkdir -p /boot/home/projects/GraphicsWorkflow/CharcoalSketchImage/PackagingFolder/data/src/CharcoalSketchImage
srcpkg=/boot/home/projects/GraphicsWorkflow/CharcoalSketchImage/PackagingFolder/data/src/CharcoalSketchImage/CharcoalSketchImage_src.zip
if test -e $srcpkg; then
	rm -f $srcpkg
fi
zip -r  $srcpkg binder/* sub/* data mainloop prologue
cd /boot/home/projects/GraphicsWorkflow/CharcoalSketchImage/PackagingFolder
addattr GraphicsWorkflow:Info "A small applet to make a charcoalsketch of an image and save the resulting image, using ImageMagick. Transparency is attempted, but will depend on the input file type. Interactive." ./apps/GraphicsWorkflow/CharcoalSketchImage
addattr GraphicsWorkflow:Info "A script to make a charcoalsketch of  an image and save the resulting image, using ImageMagick. Transparency is attempted, but will depend on the input file type. Non-Interactive." ./apps/GraphicsWorkflow/CharcoalSketchImage-Noninteractive
package create -b charcoalsketchimage_0.2-1_gcc2.hpkg
sleep 0.5
package add charcoalsketchimage_0.2-1_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Make charcoal sketch of image" charcoalsketchimage_0.2-1_gcc2.hpkg
becopy charcoalsketchimage_0.2-1_gcc2.hpkg "/Storage/Haiku/My ports"
mv charcoalsketchimage_0.2-1_gcc2.hpkg /boot/home/projects/repo2
sync
