#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/FlipImage/PackagingFolder
package create -b flipimage_0.1-1_gcc2.hpkg
sleep 0.5
package add flipimage_0.1-1_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Flip images vertically" flipimage_0.1-1_gcc2.hpkg
#becopy flipimage_0.1-1_gcc2.hpkg "/Storage/Haiku/My ports"
mv flipimage_0.1-1_gcc2.hpkg /boot/home/projects/repo2
sync