#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/AddBorderToImage/PackagingFolder
addattr GraphicsWorkflow:Info "A small applet to add a coloured border to an image and save the resulting file. Interactive" ./apps/GraphicsWorkflow/AddBorderToImage
addattr GraphicsWorkflow:Info "A script to add a coloured border to an image and save the resulting file. Non-Interactive" ./apps/GraphicsWorkflow/AddBorderToImage-Noninteractive
package create -b addbordertoimage_0.1-2_gcc2.hpkg
sleep 0.5
package add addbordertoimage_0.1-2_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "add border to images" addbordertoimage_0.1-2_gcc2.hpkg
becopy addbordertoimage_0.1-2_gcc2.hpkg "/Storage/Haiku/My ports"
mv addbordertoimage_0.1-2_gcc2.hpkg /boot/home/projects/repo2
sync


