#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/FlopImage/
mkdir -p /boot/home/projects/GraphicsWorkflow/FlopImage/PackagingFolder/data/src/FlopImage
srcpkg=/boot/home/projects/GraphicsWorkflow/FlopImage/PackagingFolder/data/src/FlopImage/FlopImage_src.zip
if test -e $srcpkg; then
	rm -f $srcpkg
fi
zip -r  $srcpkg binder/* sub/* data mainloop prologue
cd /boot/home/projects/GraphicsWorkflow/FlopImage/PackagingFolder
addattr GraphicsWorkflow:Info "A small applet to flip images horizontally and save the resulting image using ImageMagick. Interactive." ./apps/GraphicsWorkflow/FlopImage
addattr GraphicsWorkflow:Info "A script to flip images horizontally and save the resulting image using ImageMagick. Non-Interactive." ./apps/GraphicsWorkflow/FlopImage-Noninteractive
package create -b flopimage_0.2-1_gcc2.hpkg
sleep 0.5
package add flopimage_0.2-1_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Flip images horizontally" flopimage_0.2-1_gcc2.hpkg
becopy flopimage_0.2-1_gcc2.hpkg "/Storage/Haiku/My ports"
mv flopimage_0.2-1_gcc2.hpkg /boot/home/projects/repo2
sync
