#!/bin/sh
cd /boot/home/projects/GraphicsWorkflow/FlopImage/PackagingFolder
package create -b flopimage_0.1-1_gcc2.hpkg
sleep 0.5
package add flopimage_0.1-1_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "Flip images horizontally" flopimage_0.1-1_gcc2.hpkg
#becopy flopimage_0.1-1_gcc2.hpkg "/Storage/Haiku/My ports"
mv flopimage_0.1-1_gcc2.hpkg /boot/home/projects/repo2
sync